### ISSUE TITLE
Sort by layer

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym-web-dashboard#3]
Now that we're starting to get more mixnode operators in our testnet, it'd be nice to sort the list of mixnodes by which layer they're in.

**Comment by futurechimp** [comment]
I've moved this one out into cold storage until we move the directory server functionality into the Rust validator (or at least into Rust / wherever it's going to live). There's no sense in doing stuff in Go at this point, it's just waste.

**Comment by jstuczyn** [comment]
Done
